jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - id: setup-haskell-cabal
        uses: "haskell/actions/setup@v2"
        with:
          cabal-version: "${{ matrix.cabal }}"
          enable-stack: false
          ghc-version: "${{ matrix.ghc }}"
      - name: Update Hackage repository
        run: cabal update
      - name: cabal.project.local.ci
        run: |
          if [ -e cabal.project.local.ci ]; then
            cp cabal.project.local.ci cabal.project.local
          fi
      - name: freeze
        run: cabal freeze
      - uses: "actions/cache@v3"
        with:
          key: "${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('cabal.project.freeze') }}"
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
      - name: Install dependencies
        run: cabal build all --enable-tests --enable-benchmarks --only-dependencies
      - name: build all
        run: cabal build all --enable-tests --enable-benchmarks
      - name: test all
        run: cabal test all --enable-tests
      - name: haddock all
        run: cabal haddock all 
    strategy:
      matrix:
        cabal:
          - '3.4'
        ghc:
          - '9.0.2'
          - '8.10.7'
          - '8.8.4'
          - '8.6.5'
name: Haskell CI
on:
  - push
  - pull_request
